#!/bin/bash

MKDIR := mkdir -p
RM := rm -rf


GETOS := python $(NACL_SDK_ROOT)/tools/getos.py
OSNAME := $(shell $(GETOS))


PNACL_TC_PATH := $(abspath $(NACL_SDK_ROOT)/toolchain/$(OSNAME)_pnacl)
PNACL_CXX := $(PNACL_TC_PATH)/bin/pnacl-clang++

VALID_TOOLCHAINS := pnacl newlib glibc

NACL_SDK_ROOT ?= $(abspath $(CURDIR)/../../)

include $(NACL_SDK_ROOT)/tools/common.mk

TARGET = libEngineEx.so

CLIBS = ppapi_cpp ppapi

CFLAGS = -Wall 

vpath =./../../
SOURCES = $<

#	Build rules generated by macros from common.mk

$(foreach src, $(SOURCES), $(eval $(call COMPILE_RULE, $(src), $(CFLAGS))))

# The PNaCl workfow uses both an unstripped and finalized/stripped binary.
# On NaCl, onty produce a stripped binary for Release configs (not Debug)
ifneq (,$(or $(findstring pnacl,$(TOOLCHAIN)), $(findstring Release, $(CONFIG))))
$(eval $(call LINK_RULE, $(TARGET)_unsripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE, $(TARGET), $(SOURCES), $(LIBS), $(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))


all : 


clean :
